CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    member_since DATE NOT NULL
);

ALTER TABLE members
    ADD COLUMN IF NOT EXISTS password VARCHAR(255);

ALTER TABLE members
    ADD COLUMN IF NOT EXISTS current_token_id VARCHAR(255);

CREATE TABLE IF NOT EXISTS borrow_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    borrow_date DATE NOT NULL,
    return_date DATE,
    CONSTRAINT fk_borrow_records_book
        FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_borrow_records_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_borrow_per_member_book
    ON borrow_records (member_id, book_id)
    WHERE return_date IS NULL;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    borrow_record_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    is_dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_notifications_member
        FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_notifications_borrow_record
        FOREIGN KEY (borrow_record_id) REFERENCES borrow_records (id),
    CONSTRAINT uq_notification_borrow_type
        UNIQUE (borrow_record_id, notification_type)
);

ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS is_dismissed BOOLEAN NOT NULL DEFAULT FALSE;
